// Generated by CoffeeScript 1.12.7
(function() {
  var indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Meteor.autorun(function() {
    Meteor.subscribe('tasks');
    Meteor.subscribe('parents', Meteor.userId());
    Meteor.subscribe('children');
    Meteor.subscribe('myTasks', Meteor.userId());
    Meteor.subscribe('profile', Meteor.userId());
    return Meteor.subscribe('userData', Meteor.userId());
  });

  Meteor.startup(function() {});

  Handlebars.registerHelper = function(title) {
    if (title) {
      return document.title = title;
    } else {
      return document.title = "Job Jars";
    }
  };

  Template.register.events({
    'click #registerFormBtn': function(event) {
      var email, name, password, password2;
      event.preventDefault();
      name = $('#newUserFirstName').val();
      password = $('#newUserPassword').val();
      email = $('#newUserEmail').val();
      password2 = $('#newUserConfirmPassword').val();
      if (password !== password2) {
        alert('Passwords must match');
      } else {
        Accounts.createUser({
          email: email,
          password: password,
          profile: {
            name: name,
            role: "parent"
          }
        });
        Router.go('home_page');
      }
      return Account.createUser();
    }
  });

  Template.homePage.events({
    'click #registerBtnHomePage': function(e, t) {
      e.preventDefault();
      return Router.go('register');
    }
  });

  Template.loginPage.events({
    'click #btnLoginGoogle': function(e, t) {
      e.preventDefault();
      return Meteor.loginWithGoogle();
    },
    'click #btnLoginFacebook': function(e, t) {
      return e.preventDefault();
    },
    'click #btnLoginPassword': function(e, t) {
      e.preventDefault();
      return $('#login-form-div').toggle();
    },
    'click #login-button': function(e, t) {
      var email, password;
      e.preventDefault();
      email = $('#login-email').val();
      password = $('#login-password').val();
      return Meteor.loginWithPassword(email, password, function(e) {
        if (e) {
          return sweetAlert({
            title: "Oops",
            text: "There was a problem with your login. Please try again.",
            type: "error"
          });
        } else {
          return alert('Logged in');
        }
      });
    },
    'click #cancel-login-button': function(e, t) {
      e.preventDefault();
      return $('#login-form-div').hide();
    }
  });

  Template.navbar.helpers({
    'isParent': function() {
      if (Meteor.user().profile.role === "parent") {
        return true;
      } else {
        return false;
      }
    }
  });

  Template.chores.events({
    'click #addTask': function(event) {
      return $('#newTask').toggle();
    },
    'click .portlet-toggle': function(event) {
      var icon;
      icon = $(this);
      icon.toggleClass("ui-icon-minusthick ui-icon-plusthick");
      return icon.closest(".portlet").find(".portlet-content").toggle();
    }
  });

  Template.chores.rendered = function() {
    return $('#newTask').hide();
  };

  Template.myChores.rendered = function() {};

  Template.choresDone.helpers({
    'choresDone': function() {
      return Tasks.find({
        'status': 'Done'
      });
    }
  });

  Template.myChores.helpers({
    'tasks': function() {
      return Tasks.find({
        available: true
      });
    },
    'mines': function() {
      return Children.find({
        userId: Meteor.userId()
      });
    },
    'dones': function() {
      return Children.find({}, {
        fields: {
          'completedTasks': 1
        }
      });
    }
  });

  Template.my_task.helpers({
    'task': function() {
      return this['myTasks'][0]['task'];
    },
    'task_id': function() {
      return this['myTasks'][0]['task_id'];
    },
    'desc': function() {
      return this['myTasks'][0]['desc'];
    },
    'value': function() {
      return this['myTasks'][0]['value'];
    }
  });

  Template.myChores.events({
    'dragstart .chore': function(e) {
      e.dataTransfer = e.originalEvent.dataTransfer;
      return e.dataTransfer.setData('text', e.target.id);
    },
    'dragover #available-chores,#jar,#mine': function(e) {
      return e.preventDefault();
    },
    'drop #available-chores,#jar,#mine': function(e) {
      var elementID, id, ref, ref1, targetID, validNodes;
      e.dataTransfer = e.originalEvent.dataTransfer;
      id = e.dataTransfer.getData('text');
      elementID = document.getElementById(id);
      validNodes = ['jar', 'mine', 'available-chores'];
      if ((ref = e.target.id, indexOf.call(validNodes, ref) >= 0)) {
        e.target.appendChild(elementID);
        targetID = e.target.id;
      } else if ((ref1 = e.target.parentNode, indexOf.call(validNodes, ref1) >= 0)) {
        e.target.parentNode.appendChild(elementID);
        targetID = e.target.parentNode.id;
      }
      return e.preventDefault();
    }
  });

  Template.children.events({
    'click #addChild': function(event) {
      return $('#newChild').toggle();
    }
  });

  Template.children.helpers({
    'child': function() {
      return Children.find({
        childOf: Meteor.userId()
      });
    }
  });

  Template.children.rendered = function() {
    return $('#newChild').hide();
  };

  Template.childrenList.helpers({
    'child': function() {
      return Children.find({
        childOf: Meteor.userId()
      });
    }
  });

  Template.childrenList.events({
    'click #addChild': function(event) {
      return $('#newChild').toggle();
    }
  });

  Template.rewardsEarned.rendered = function() {};

  Template.rewardsEarned.events({
    'click .btn': function(e, t) {
      e.preventDefault();
      return alert('Reward button clicked');
    }
  });

  Template.addTask.events({
    'submit': function() {
      return alert($('#taskDesc').val());
    }
  });

  Template.addChild.events;

  Template.addChild.events({
    'click #btnAddChild': function(e, t) {
      var dob, name, password, username;
      e.preventDefault();
      name = $('#childName').val();
      dob = $('#childDob').val();
      username = $('#childUserName').val();
      password = $('#childPassword').val();
      Meteor.call('createChild', name, username, password, dob, Meteor.userId());
      return $('#newChild').hide();
    },
    'click #closeAddChildBox': function(e) {
      e.preventDefault();
      return $('#newChild').hide();
    }
  });

  Template.chores.helpers({
    tasks: function() {
      var myParentId;
      myParentId = Children.find({
        _id: Meteor.userId()
      }, {
        fields: {
          _id: 0,
          childOf: 1
        }
      });
      return Tasks.find({
        createdBy: myParentId
      });
    }
  });

  $(".column").sortable({
    connectWith: ".column",
    handle: ".portlet-header",
    cancel: ".portlet-toggle",
    start: function(event, ui) {
      ui.item.addClass('tilt');
      return tilt_direction(ui.item);
    },
    stop: function(event, ui) {
      ui.item.removeClass("tilt");
      $("html").unbind('mousemove', ui.item.data("move_handler"));
      return ui.item.removeData("move_handler");
    }
  });

  $(".portlet").addClass("ui-widget ui-widget-content ui-helper-clearfix ui-corner-all").find(".portlet-header").addClass("ui-widget-header ui-corner-all").prepend("<span class='ui-icon ui-icon-minusthick portlet-toggle'></span>");

  Template.profile.helpers({
    'name': function() {
      if ((Meteor.user().services.google)) {
        return Meteor.user().services.google.name;
      } else if (Meteor.user().services.password) {
        return Meteor.user().profile.name;
      }
    },
    'email': function() {
      if ((Meteor.user().services.google)) {
        return Meteor.user().services.google.email;
      } else if (Meteor.user().services.password) {
        return Meteor.user().emails[0]['address'];
      }
    }
  });

  Template.profile.events({
    'click #btn-edit-profile': function() {
      return Router.go('editProfile');
    }
  });

  Template.coming_soon.rendered = function() {
    $('.navbar').hide();
    $('body').css('background-image', "url('/child_raking.jpg')");
    $('body').css('background-repeat', 'no-repeat');
    return $('body').css('background-color', '#ffffff');
  };

}).call(this);

//# sourceMappingURL=job_jar_template_support.js.map
